<a href="https://colab.research.google.com/github/Abhinanda24/LLM_lab/blob/main/Experiment_no_3_clean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
model_checkpoint = 'distilbert-base-uncased-finetuned-sst-2-english'
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(model_checkpoint)
print(f"Tokenizer loaded for model: {model_checkpoint}")
print(f"Model loaded for sequence classification: {model_checkpoint}")
text_input = "This movie is absolutely fantastic! I loved every moment of it."
inputs = tokenizer(text_input, return_tensors='pt', truncation=True)
print("Original text input:")
print(text_input)
print("\nTokenized input (PyTorch tensors):")
print(inputs)
import torch.nn.functional as F
import torch
outputs = model(**inputs)
logits = outputs.logits
probabilities = F.softmax(logits, dim=-1)
predicted_class_id = torch.argmax(probabilities, dim=-1)
print("Model Outputs (logits):")
print(logits)
print("\nProbabilities:")
print(probabilities)
print("\nPredicted Class ID:")
print(predicted_class_id)
predicted_label = model.config.id2label[predicted_class_id.item()]
print(f"Predicted Label: {predicted_label}")
print(f"The sentiment of the input text is: {predicted_label}")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

Tokenizer loaded for model: distilbert-base-uncased-finetuned-sst-2-english
Model loaded for sequence classification: distilbert-base-uncased-finetuned-sst-2-english
Original text input:
This movie is absolutely fantastic! I loved every moment of it.

Tokenized input (PyTorch tensors):
{'input_ids': tensor([[  101,  2023,  3185,  2003,  7078, 10392,   999,  1045,  3866,  2296,
          2617,  1997,  2009,  1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}
Model Outputs (logits):
tensor([[-4.3539,  4.7132]], grad_fn=<AddmmBackward0>)

Probabilities:
tensor([[1.1539e-04, 9.9988e-01]], grad_fn=<SoftmaxBackward0>)

Predicted Class ID:
tensor([1])
Predicted Label: POSITIVE
The sentiment of the input text is: POSITIVE
